---
- name: Global proxy configuration
  blockinfile:
    name: /etc/profile
    block: |
      export HTTP_PROXY=http://bastion:3128/
      export HTTPS_PROXY=http://bastion:3128/

- name: Global proxy configuration
  blockinfile:
    name: /etc/environment
    block: |
      export HTTP_PROXY=http://bastion:3128/
      export HTTPS_PROXY=http://bastion:3128/

- name: Proxy configuration for apt
  blockinfile:
    name: /etc/apt/apt.conf.d/proxy.conf
    block: |
      Acquire {
        HTTP::proxy "http://bastion:3128";
        HTTPS::proxy "http://bastion:3128";
      }
    create: yes

- name: Proxy configuration for wget
  lineinfile:
    path: /etc/wgetrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#http_proxy' , line: 'http_proxy = http://bastion:3128' }
    - { regexp: '^#https_proxy' , line: 'https_proxy = http://bastion:3128' }
    - { regexp: '^use_proxy' , line: 'use_proxy = yes' }
