---
- name: Install Grafana
  hosts: grafana
  become: yes

  tasks:
  - include_tasks: setup/setup.yaml
  - include_tasks: setup/upgrade.yaml

  - name: Download libfontconfig1
    command: apt-get install -y adduser libfontconfig1 lsb-release

  - name: apt --fix-broken install
    command: apt --fix-broken install  
    
  - name: Download Grafana
    get_url:
      url: https://dl.grafana.com/oss/release/grafana_8.5.3_amd64.deb
      dest: /home/admin

  - name: Install Grafana
    shell: dpkg -i grafana_8.5.3_amd64.deb
    register: packages

  - name: Enable Grafana service
    service:
      name: grafana-server
      state: started
      enabled: yes
