---
- name: Prometheus configuration
  hosts: prom
  become: yes

  environment:
    HTTP_PROXY: http://bastion:3128
    HTTPS_PROXY: http://bastion:3128

  tasks:
  - include_tasks: setup/setup.yaml
  - include_tasks: setup/proxy.yaml
  - include_tasks: setup/upgrade.yaml

  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz
      dest: /home/admin/
      use_proxy: yes

  - name: Copy Prometheus yml
    copy:
      src: "{{ pwd }}/ansible/configs/prometheus.yml"
      dest: /home/admin/

  - name: Unarchive Prometheus
    unarchive:
      src: /home/admin/prometheus-2.36.2.linux-amd64.tar.gz
      dest: /home/admin/
      remote_src: yes

  - name: Create Prometheus user
    user:
      name: prometheus
      create_home: no
      shell: /bin/false
      append: no

  - name: Create directories for Prometheus
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/prometheus 
      - /var/lib/prometheus

  - name: Copy Prometheus files in directories
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
    with_items:
      - { src: /home/admin/prometheus-2.36.2.linux-amd64/promtool , dest: /usr/local/bin }
      - { src: /home/admin/prometheus-2.36.2.linux-amd64/prometheus , dest: /usr/local/bin }
      - { src: /home/admin/prometheus-2.36.2.linux-amd64/console_libraries , dest: /etc/prometheus }
      - { src: /home/admin/prometheus-2.36.2.linux-amd64/consoles , dest: /etc/prometheus }
      - { src: /home/admin/prometheus.yml , dest: /etc/prometheus }
      
  - name: Change Prometheus files ownership (/etc/prometheus and /var/lib/prometheus)
    file:
      path: "{{ item }}"
      owner: prometheus
      group: prometheus
      recurse: yes
    with_items:
      - /etc/prometheus
      - /var/lib/prometheus

  - name: Change Prometheus files ownership (/usr/local/bin/prometheus and /usr/local/bin/promtool)
    file:
      path: "{{ item }}"
      owner: prometheus
      group: prometheus
    with_items:
      - /usr/local/bin/prometheus
      - /usr/local/bin/promtool

  - name: Make prometeus files executable 
    command: chmod -c -R ugo=rwx "{{ item }}"
    with_items:
      - /usr/local/bin/prometheus
      - /usr/local/bin/promtool
  
  - name: Create prometheus.service file
    blockinfile:
      path: /etc/systemd/system/prometheus.service
      block: |
        [Unit]
        Description=Prometheus Service
        After=network.target
        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries
        ExecReload=/bin/kill -HUP $MAINPID Restart=on-failure
        [Install]
        WantedBy=multi-user.target
      create: yes

  - name: Enable and start Prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
